import type { Category } from "./types";
import {
  CarFront,
  Smile,
  ChefHat,
  Hospital,
  Gamepad2,
  ShoppingBag,
  Wifi,
  Coffee,
  Utensils,
  Pizza,
  Beer,
  IceCream,
  ShoppingCart,
  Tag,
  Gift,
  Bus,
  Train,
  Bike,
  Plane,
  Music,
  Film,
  Camera,
  Tv,
  Wallet,
  Banknote,
  CreditCard,
  Landmark,
  Heart,
  Activity,
  Stethoscope,
  Pill,
} from "lucide-react";

export const ALL_CATEGORY_ICONS_MAP = {
  chefHat: ChefHat,
  shoppingBag: ShoppingBag,
  carFront: CarFront,
  gamepad2: Gamepad2,
  hospital: Hospital,
  smile: Smile,
  wifi: Wifi,
  coffee: Coffee,
  utensils: Utensils,
  pizza: Pizza,
  beer: Beer,
  iceCream: IceCream,
  shoppingCart: ShoppingCart,
  tag: Tag,
  gift: Gift,
  bus: Bus,
  train: Train,
  bike: Bike,
  plane: Plane,
  music: Music,
  film: Film,
  camera: Camera,
  tv: Tv,
  wallet: Wallet,
  banknote: Banknote,
  creditCard: CreditCard,
  landmark: Landmark,
  heart: Heart,
  activity: Activity,
  stethoscope: Stethoscope,
  pill: Pill,
};

export const ALL_CATEGORY_ICON_KEYS = Object.keys(
  ALL_CATEGORY_ICONS_MAP
) as (keyof typeof ALL_CATEGORY_ICONS_MAP)[];

export const DEFAULT_CATEGORY_ID = "0";

export const DEFAULT_CATEGORIES: Category[] = [
  {
    id: DEFAULT_CATEGORY_ID,
    name: "Default",
    iconKey: "smile",
    createdAt: Date.now(),
    isSystem: true,
  },
  { id: "1", name: "Meals", iconKey: "chefHat", createdAt: Date.now() },
  { id: "2", name: "Shopping", iconKey: "shoppingBag", createdAt: Date.now() },
  { id: "3", name: "Transport", iconKey: "carFront", createdAt: Date.now() },
  {
    id: "4",
    name: "Entertainment",
    iconKey: "gamepad2",
    createdAt: Date.now(),
  },
  { id: "5", name: "Medical", iconKey: "hospital", createdAt: Date.now() },
];
